language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master
    - dev

cache: yarn

script:
  - yarn
  - yarn lint

deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: thomas-delachaux
    app: ua-bouffe-fork
    token: $OPENSHIFT_TOKEN
    on:
      branch: master
    edge: true
